language: rust
os:
- osx
- linux
- windows

before_script:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        git clone https://github.com/microsoft/vcpkg
        cd vcpkg
        ./bootstrap-vcpkg.bat
        ./vcpkg integrate install
        ./vcpkg install openssl:x64-windows
        export VCPKGRS_DYNAMIC=1
    esac
jobs:
  include:
  - language: minimal
    os: linux
    services: docker
    script: docker build .

