[package]
name = "resweb"
version = "0.1.0"
authors = ["Pachler, Uwe <uwe.pachler@datagroup.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version="1.3.0", features=["full"]}
actix-web = "3.3.2"
actix-web-httpauth = "0.5.0"
serde = "1.0.124"
alcoholic_jwt = "1.0.0"
reqwest = {version="0.11.2", features=["json"]}
juniper = "0.15"
juniper_actix = "0.2"